#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/project_3
#    username: postgres
#    password: 10112001
#
#  # Cấu hình JPA
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comment: true
#        format_sql: true


